### ISSUE TITLE
Unable to receive inbound messages via webhook

### ISSUE THREAD

**Issue by delattre1** [sendblue-api/sendblue-api.github.io#9]
Hi,

I've been testing your API and encountered an issue when trying to receive inbound messages.

### Steps Taken:
1. **Outbound Messages**:  
   - I successfully sent a message using the `/send-message` route and provided a `status_callback` URL to receive status updates.  
   - I have a FastAPI server exposed via ngrok that handles the status callback, and this works as expected.

2. **Inbound Messages via Webhook**:  
   - On the same server, I created a simple `/webhook` route and registered it in the [API Dashboard](https://app.sendblue.co/api-dashboard) under the Webhooks section.  
   - According to the documentation, received messages should be sent as a POST request to the webhook defined in the API dashboard:
   
     > "In order to enable receiving messages, you have to specify the webhooks that you want to use in your API dashboard. Received messages will be sent as a POST request to the webhook which you define."

However, when I send a message to the Sendblue robot number from my device, I don’t receive any requests at my webhook.

Additionally, when I use the `/messages` route to list messages, all the returned messages have the `isOutbound` property set to `true`, so I can't see any messages I've sent from my phone.

### Question:
Is this behavior expected?  
Do I need to subscribe to a different plan to access inbound messages?

Thank you!

**Comment by njerschow** [comment]
On the shared tier, you will run into the issue you described **only if** you have never sent yourself a message from your Sendblue Account. If you aren't receiving inbound webhooks once the communication has been established on the shared plan, please send us an email with your information @ support@sendblue.co 

FYI we are also deprecating shared number plans in favor of dedicated plans. You will have no inbound restrictions on the dedicated plan - we typically recommend this going forward for higher reliability.

**Comment by delattre1** [comment]
Yeah, the problem is that this happened after I had already sent messages from my phone to the shared SendBlue number. I completed the verification step by giving a thumbs up to the message and received the `'Congratulations! Your number has been verified'` confirmation, but it still didn't work.

**Comment by delattre1** [comment]
Can you confirm if simply upgrading from the Sapphire to the Lapis plan will give us access to a dedicated line, or if an additional setup is required?
